# Generated by Django 3.0.5 on 2020-11-17 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cmanage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('effect', models.CharField(max_length=100)),
                ('rollback', models.CharField(max_length=100)),
                ('statu', models.CharField(max_length=10)),
                ('author', models.CharField(max_length=20)),
                ('cdate', models.DateField(auto_now_add=True)),
                ('ctime', models.CharField(max_length=20)),
                ('witime', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=20)),
                ('reviewer', models.CharField(max_length=20)),
                ('confirm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirname', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('parentid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('createtime', models.CharField(max_length=20)),
                ('editortime', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(blank=True, max_length=20, null=True)),
                ('server_type', models.CharField(blank=True, max_length=10, null=True)),
                ('hostname', models.CharField(blank=True, max_length=50, null=True)),
                ('system_version', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('kernel', models.CharField(blank=True, max_length=50, null=True)),
                ('core_quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('memory', models.CharField(blank=True, max_length=10, null=True)),
                ('hdd', models.CharField(blank=True, max_length=10, null=True)),
                ('vlan', models.CharField(blank=True, max_length=10, null=True)),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('esxi_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('zbx_stau', models.CharField(blank=True, max_length=20, null=True)),
                ('application', models.CharField(blank=True, max_length=100, null=True)),
                ('administrator', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Progroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(max_length=20, unique=True)),
                ('brand', models.CharField(max_length=20)),
                ('servername', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('cpu_model', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu_quantity', models.CharField(max_length=10)),
                ('cpu_core', models.CharField(max_length=10)),
                ('memory_quantity', models.CharField(max_length=10)),
                ('memory_total', models.CharField(max_length=10)),
                ('ssd_quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('ssd_total', models.CharField(blank=True, max_length=10, null=True)),
                ('hdd_quantity', models.CharField(blank=True, max_length=10, null=True)),
                ('hdd_total', models.CharField(blank=True, max_length=10, null=True)),
                ('raid_type', models.CharField(blank=True, max_length=10, null=True)),
                ('idrac_ip', models.CharField(blank=True, max_length=20, null=True)),
                ('purchase_date', models.CharField(blank=True, max_length=20, null=True)),
                ('warranty_end', models.CharField(blank=True, max_length=20, null=True)),
                ('function', models.CharField(blank=True, max_length=50, null=True)),
                ('data_center', models.CharField(max_length=20)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('idrac_network', models.CharField(blank=True, max_length=100, null=True)),
                ('rack', models.CharField(max_length=10)),
                ('rack_u', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usergroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ops.Progroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Properm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ops.Progroup')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ops.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ops.Directory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('createtime', models.CharField(max_length=20)),
                ('editortime', models.CharField(blank=True, max_length=20, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ops.Directory')),
            ],
        ),
    ]
