# Generated by Django 3.0.5 on 2020-11-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properm',
            name='perm',
            field=models.CharField(max_length=5),
        ),
    ]
