# Generated by Django 3.0.5 on 2020-11-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ops', '0002_auto_20201120_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directory',
            unique_together={('dirname', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('directory', 'filename')},
        ),
    ]
