# Generated by Django 3.0.5 on 2020-11-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ops', '0003_auto_20201121_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content',
        ),
        migrations.AddField(
            model_name='document',
            name='filepath',
            field=models.CharField(default=131, max_length=50),
            preserve_default=False,
        ),
    ]
